name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend (Main API)
        run: |
          curl -s --max-time 10 https://finqa-app-w15r.onrender.com/health || echo "❌ Failed to ping main backend"

      - name: Ping Backend (Auth API & DB)
        run: |
          curl -s --max-time 10 https://finqa-auth-app-ac1o.onrender.com/health/db || echo "❌ Failed to ping auth backend DB"

      - name: Ping Frontend
        run: |
          curl -s --max-time 10 https://wealthwizai.netlify.app/ || echo "❌ Failed to ping frontend"